# Generated by Django 5.2.4 on 2025-08-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendinguser_remove_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
