# Generated by Django 5.2.4 on 2025-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
