# Generated by Django 5.2.4 on 2025-09-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_finalorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='order',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='orders',
            field=models.ManyToManyField(related_name='final_orders', to='orders.order'),
        ),
    ]
