# Generated by Django 5.2.4 on 2025-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
