# Generated by Django 5.2.4 on 2025-09-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_finalorder_order_finalorder_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
