# Generated by Django 5.2.3 on 2025-08-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
        ('orders', '0004_order_seen_by_admin'),
    ]

    operations = [
    ]
