# Generated by Django 5.2.4 on 2025-08-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image_is_main'),
        ('products', '0002_product_is_active_product_tags'),
    ]

    operations = [
    ]
