# Generated by Django 5.2.4 on 2025-08-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20250821_1810'),
        ('products', '0003_merge_20250821_2130'),
    ]

    operations = [
    ]
